name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
  schedule:
    - cron: '0 2 * * 1' # At 02:00 on Monday

jobs:
  test:
    name: Test
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [10.x, 12.x, 14.x]
        include:
          - os: macos-latest
            node-version: 14
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Bootstrap project
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Run tests
        run: npm run test:ci
      - name: Run coverage
        run: npm run coverage:ci
      - name: Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '14.x'
        uses: coverallsapp/github-action@1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  code-lint:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Bootstrap project
        run: |
          npm ci
      - name: Build project
        run: npm run build
      - name: Verify code linting
        run: npm run lint
